# -*- coding: utf-8 -*-
"""SqueezeBERT_Aditya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jj0yDuvjK38NwvAk-eIMv2DOVT8i33-i
"""

!git clone https://gitlab.com/bottle_shop/safe/prompthate.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/prompthate/PromptHate-Code/

!bash run.sh

