# -*- coding: utf-8 -*-
"""ROBERTA_default.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VnTeiFocYbuZxEAWNmqgmj0ukYI3a8B4
"""

!nvidia-smi

!git clone https://gitlab.com/bottle_shop/safe/prompthate

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/prompthate/PromptHate-Code/

# Commented out IPython magic to ensure Python compatibility.
# %ls

!bash run.sh